### ISSUE TITLE
How to build LittleFileSystem on Keil

### ISSUE THREAD

**Issue by olavipartanen** [geky/littlefs#14]
When building littlefilesystem with Keil I get following error:
Error: L6218E: Undefined symbol __builtin_ctz (referred from lfs.o).

How to build littlefs on Keil?

**Comment by geky** [comment]
I'm guessing from the name this is on Mbed OS?

related https://github.com/ARMmbed/mbed-os/issues/5935, https://github.com/geky/littlefs/issues/6

**Comment by geky** [comment]
This has since been fixed in littlefs mainline: https://github.com/geky/littlefs/commit/4f08424b51c6e7fda140b91fd551a35531ca0fc3

Feel free to reopen if this needs work.
