### ISSUE TITLE
C++ include

### ISSUE THREAD

**Issue by sn00pster** [geky/littlefs#32]
Can we have a:

#ifdef __cplusplus
extern "C" {
#endif

.....

#ifdef __cplusplus
}
#endif

in the include file so it can be cleanly included by a cpp file?

**Comment by geky** [comment]
Why not specify `extern "C"` in the C++ file?
https://github.com/ARMmbed/mbed-littlefs/blob/33a2ca519a5b2c3b97db15852721081340a2fdb1/LittleFileSystem.h#L22-L24

Seems a bit strange that a C library needs to support C++ and not the other way around.

**Comment by sn00pster** [comment]
That's what I do, I personally just find it neater using an ifdef and extern "C" combo inside header files as it means you can just include it blindly from C or C++ without having to think.

Guess it's personal preference.

**Comment by sn00pster** [comment]
On a complete tangent, I was looking at the little fs class in mbed and I couldn't for the life of me see where it allocated space for the file structure, it just uses a void * and doesn't seem to allocate it anywhere.  Don't know if that was your code and I didn't dig that deep so I probably missed the important bit.

**Comment by geky** [comment]
Ah, it allocates the file structure in `file_open` using C++'s new operator, which makes it a bit harder to find:
https://github.com/ARMmbed/mbed-os/blob/master/features/filesystem/littlefs/LittleFileSystem.cpp#L372

One of the trickier parts of file-memory-management is that the file structure must be deleted in `file_close`, even if an error occurs:
https://github.com/ARMmbed/mbed-os/blob/master/features/filesystem/littlefs/LittleFileSystem.cpp#L394

**Comment by geky** [comment]
I'm going to go ahead and close this, feel free to reopen if you want
