### ISSUE TITLE
Positive offset for LFS_SEEK_CUR always fails

### ISSUE THREAD

**Issue by roceh** [geky/littlefs#4]
If you seek backwards then try to seek forwards using LFS_SEEK_CUR it fails with LFS_ERR_INVAL.

**Comment by geky** [comment]
Hi @roceh, thanks for reporting the issue. I'm surprised this sort of bug went unnoticed until now.

I've pushed up a patch, so it should be fixed now: https://github.com/geky/littlefs/commit/aea3d3db46634bf26298c8df0be020c03b80daba
